block: IRON_BLOCK
# The base block to modify. Please refer to "Block Providers"
# on the wiki for more information about what you can put here.

breaking-time: # This value is in ticks!
  max: 30 # The maximum amount of ticks it should take to break the block
  min: 10 # The minimum amount of ticks it should take to break the block
  base: 20 # This value is optional! If not specified, the base value will use the max breaking time.
  # The base value is the time it takes to break the block if no states have activated.

states: # Please refer to "Break States" on the wiki.
- permission{node="rank.vip";value=5;} # Will subtract 5 ticks from the breaking time.
- mmolevel{level=12;} # Will use the default "value" of '1'
# If both of the above states activate then the total breaking time in ticks will become 14, since
# the base value is 20 and the permission state subtracts 5 ticks and the mmolevel state subtracts 1 tick.

triggers: # Please refer to "Break Triggers" on the wiki.
- start{skill="MyThiccSkill";}
# Will execute a MythicMobs skill called "MyThiccSkill" when the
# player starts breaking the block (if the skill can be found).
# Possible triggers are: start, stage, stop, break, abort
# More information about each trigger is available on the wiki.
# REQUIRES MYTHICMOBS